# Generated by Django 6.0 on 2025-12-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_patientprofile_address_alter_patientprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='complaints',
            field=models.TextField(blank=True, default=''),
        ),
    ]
