# Generated by Django 6.0 on 2025-12-05 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_patientprofile_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 5, 11, 57, 32, 110826, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
